name: build and test on aarch64
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  test-on-macos-aarch64:
    strategy:
      matrix:
        build: [
          {name: "release", cargo_flags: "--release",  timeout_multiplier: 1},
          {name: "debug", cargo_flags: "", timeout_multiplier: 10},
        ]
    runs-on: macos-14
    name: test on macos-14-aarch64
    steps:
      - name: install prerequisites
        run: |
          brew install meson
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: cache rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: arm-darwin-cargo-and-target-${{ hashFiles('**/Cargo.lock') }}
      - name: cargo ${{ matrix.build.name }} build for aarch64-apple-darwin
        run:  cargo build ${{ matrix.build.cargo_flags }}
      - name: test ${{ matrix.build.name }} build without frame delay
        run: |
          .github/workflows/test.sh \
            -r ./target/${{ matrix.build.name }}/dav1d \
            -s ./target/${{ matrix.build.name }}/seek_stress \
            -t ${{ matrix.build.timeout_multiplier }}
        # release tests run quickly so also cover the frame delay cases
      - name: test release build with frame delay of 1
        if: ${{ matrix.build.name == 'release' }}
        run: |
          .github/workflows/test.sh \
            -r ./target/release/dav1d \
            -s ./target/release/seek_stress \
            -f 1
      - name: test release build with frame delay of 2
        if: ${{ matrix.build.name == 'release' }}
        run: |
          .github/workflows/test.sh \
            -r ./target/release/dav1d \
            -s ./target/release/seek_stress \
            -f 2
      - name: copy log files
        if: ${{ !cancelled() }}
        run: |
          cp ${{ github.workspace }}/build/meson-logs/testlog.txt \
              ${{ github.workspace }}/build/meson-logs/testlog-aarch64-apple-darwin-${{ matrix.build.name }}.txt
      - name: upload build artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: meson-test-logs-aarch64-apple-darwin-${{ matrix.build.name }}
          path: |
            ${{ github.workspace }}/build/meson-logs/testlog-*.txt
